// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_residuals_cpp
List calculate_residuals_cpp(NumericVector R_j, IntegerVector indexes, IntegerVector indexesStar, int num_levels_old, int num_centres_new);
RcppExport SEXP _AddiVortes_calculate_residuals_cpp(SEXP R_jSEXP, SEXP indexesSEXP, SEXP indexesStarSEXP, SEXP num_levels_oldSEXP, SEXP num_centres_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type R_j(R_jSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indexesStar(indexesStarSEXP);
    Rcpp::traits::input_parameter< int >::type num_levels_old(num_levels_oldSEXP);
    Rcpp::traits::input_parameter< int >::type num_centres_new(num_centres_newSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_residuals_cpp(R_j, indexes, indexesStar, num_levels_old, num_centres_new));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AddiVortes_calculate_residuals_cpp", (DL_FUNC) &_AddiVortes_calculate_residuals_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_AddiVortes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
