# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_residuals_cpp <- function(R_j, indexes, indexesStar, num_levels_old, num_centres_new) {
    .Call(`_AddiVortes_calculate_residuals_cpp`, R_j, indexes, indexesStar, num_levels_old, num_centres_new)
}

propose_tessellation_cpp <- function(tess_j, dim_j, var, numCovariates) {
    .Call(`_AddiVortes_propose_tessellation_cpp`, tess_j, dim_j, var, numCovariates)
}

