# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers in C++
NULL

add_numbers_cpp <- function(x, y) {
    .Call(`_AddiVortes_add_numbers_cpp`, x, y)
}

